/obj/item/mecha_parts/exosuit_transmission
	name = "exosuit transmission"
	desc = "Converts engine revs into motive force. Lower gears favor acceleration, higher gears favor top speed."
	icon = 'icons/mecha/mecha_equipment.dmi'
	icon_state = "mecha_transmission"
	max_integrity = 100

	var/obj/vehicle/sealed/mecha/ntf/ntf_chassis

	var/current_gear = GEAR_0
	var/previous_gear
	var/gear_types = list(GEAR_0, GEAR_1, GEAR_2, GEAR_3)

	var/gear_efficieny_health = 1

	var/gear_efficiency_gaining = 0.75 // How efficiently revs are loaded into inertia
	var/gear_efficiency_loading = 0.5 // Inertia to load gets loaded into this

	var/is_connected = FALSE // If it's actually in a mech / engine or not

	var/obj/vehicle/sealed/mecha/ntf/ntf_chassis

	var/inertia_to_load = 0 // 0-10, presumably turned into negative speed/lower movedelay through some arcane arts
	var/current_inertia
	var/max_inertia = 20

	var/gear_translation = GEAR_0 // Translates how much of the revs into acceleration, vs not into acceleration, but increasing the max speed

/*


So what do gears do? I think the trans can be a box, that has different gears. Hm.. The "translation" of revs > gear > outputted power should be based in the engines.dm . Or here, actually.
What should go into transmission.dm? Hm..
Gear status, and gear calculation, I guess.
Proc for changing gears
Proc for attempting a damaging shift-launch (high revs at gear 0 > high revs at gear <1)
Proc for ???
Inertia is stored on the engine/trans, and then it's given to the mech, which uses it in mecha_movement.dm
Inertia is generated by taking the engine's revs directly and translating them into inertia, which hm... updates on the gear's side? And the gear's inertia var is pushed to the mech?


*/
/*
/obj/item/mecha_parts/exosuit_transmission/proc/gear_up(next_gear)
	if(current_gear == next_gear)
		return
	current_gear++

/obj/item/mecha_parts/exosuit_transmission/proc/gear_down(next_gear)
	if(current_gear == next_gear)
		return
	current_gear--

/obj/item/mecha_parts/exosuit_transmission/proc/convert_revs(revs)
	if(ntf_chassis && ntf_chassis.body.engine?.is_functional)
		var/engine = ntf_chassis.body.engine
		inertia_to_load = (min(engine.revs * (gear_efficiency_base * gear_efficieny_health) / 10), max_inertia)

/obj/item/mecha_parts/exosuit_transmission/proc/set_gear_output()
	if(ntf_chassis && ntf_chassis.body.engine?.is_functional)


/obj/item/mecha_parts/exosuit_transmission/proc/check_components()

/obj/item/mecha_parts/exosuit_transmission/process()
	if(!inertia_to_load)
		stop_processing()
		return
	start_processing()
*/
